# Generated by Django 4.1.13 on 2024-04-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=100)),
                ('caption', models.CharField(max_length=1000)),
                ('image', models.CharField(max_length=10000)),
                ('location', models.CharField(max_length=100)),
                ('tags', models.CharField(max_length=100)),
                ('createdAt', models.CharField(max_length=100)),
                ('likes', models.CharField(blank=True, default='', max_length=100000000)),
                ('postId', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
