# Generated by Django 4.1.13 on 2024-04-28 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_delete_savepost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
