# Generated by Django 4.1.13 on 2024-04-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=100)),
                ('caption', models.CharField(max_length=1000)),
                ('image', models.CharField(max_length=100000000)),
                ('location', models.CharField(max_length=100)),
                ('tags', models.CharField(max_length=100)),
                ('createdAt', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SavePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=100)),
                ('caption', models.CharField(max_length=1000)),
                ('image', models.CharField(max_length=100000000000)),
                ('location', models.CharField(max_length=100)),
                ('tags', models.CharField(max_length=100)),
                ('createdAt', models.CharField(max_length=100)),
                ('postId', models.IntegerField()),
            ],
        ),
    ]
